services:
  - type: web
    name: projetofly-mercadolivre
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MELI_CLIENT_ID
        sync: false
      - key: MELI_CLIENT_SECRET
        sync: false
      - key: MELI_REDIRECT_URI
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_API_KEY
        generateValue: true
      - key: PUBLIC_BASE_URL
        sync: false
